name: Build & Test

on: [push, pull_request]

jobs:
  build-asm:
    name: ASM.js Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@v14
      - run: make all
      - run: node dist/jurischain-cli.js 5 CI_Seed

  test-docker:
    name: Docker Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./build.sh test
